export const SOCKET_URL = import.meta.env.VITE_SOCKET_URL || 'https://voice-chat.vachagan.dev';

export const EVENTS = {
  // Connection
  CONNECT: 'connect',
  DISCONNECT: 'disconnect',
  CONNECT_ERROR: 'connect_error',
  ERROR: 'error',

  // Client -> Server
  SEND_MESSAGE: 'send_message',
  MESSAGE_DELIVERED: 'message_delivered',
  MESSAGE_READ: 'message_read',
  CONVERSATION_READ: 'conversation_read',
  CLIENT_TYPING_START: 'typing_start',
  CLIENT_TYPING_STOP: 'typing_stop',
  CLIENT_PRESENCE_STATE: 'presence_state',
  CALL_JOIN: 'call.join',
  CALL_MEDIA_STATE: 'call.media_state',
  CALL_OFFER: 'call.offer',
  CALL_ANSWER: 'call.answer',
  CALL_ICE_CANDIDATE: 'call.ice_candidate',
  CALL_CONNECTED: 'call.connected',
  CALL_HANGUP: 'call.hangup',
  CALL_REJECT: 'call.reject',
  CALL_RESUME: 'call.resume',

  // Server -> Client
  RECEIVE_MESSAGE: 'receive_message',
  MESSAGE_STATUS: 'message_status',
  MESSAGE_ACK: 'message_ack',
  MESSAGE_EDITED: 'message_edited',
  MESSAGE_DELETED: 'message_deleted',
  MESSAGE_REACTED: 'message_reacted',
  POLL_UPDATED: 'poll_updated',
  THREAD_REPLY_CREATED: 'thread_reply_created',
  THREAD_SUMMARY_UPDATED: 'thread_summary_updated',
  CONVERSATION_PINS_UPDATED: 'conversation_pins_updated',
  CONVERSATION_HISTORY_CLEARED: 'conversation_history_cleared',
  PRESENCE_UPDATE: 'presence_update',
  USER_ONLINE: 'user_online', // Keeping these if they are part of presence_update or separate
  USER_OFFLINE: 'user_offline',
  SERVER_TYPING_START: 'typing_start',
  SERVER_TYPING_STOP: 'typing_stop',
  RELATIONSHIP_REQUESTED: 'relationship.requested',
  RELATIONSHIP_ACTIVATED: 'relationship.activated',
  RELATIONSHIP_REVOKED: 'relationship.revoked',
  BLOCK_CREATED: 'block.created',
  BLOCK_REMOVED: 'block.removed',
  SPACE_INVITE: 'space:invite',
  CALL_INCOMING: 'call.incoming',
  CALL_ACCEPTED: 'call.accepted',
  CALL_PARTICIPANT_UPDATED: 'call.participant_updated',
  CALL_REJECTED: 'call.rejected',
  CALL_RECOVERY_AVAILABLE: 'call.recovery_available',
  CALL_RECONNECTING: 'call.reconnecting',
  CALL_RESUMED: 'call.resumed',
  CALL_ENDED: 'call.ended',
} as const;
